### ISSUE TITLE
Anyone working on improving this SDK?

### ISSUE THREAD

**Issue by walsht** [Livefyre/StreamHub-iOS-SDK#75]
Anyone working on improving this SDK?

**Comment by gibron** [comment]
@walsht The SDK is being contributed to at a slower pace at the moment but we do have improvements to it on our roadmap. If you have specific requests let us know; happy to pick this up over email as well, gibron@livefyre.com. Looking forward to hearing from you.

**Comment by gibron** [comment]
@walsht I am going to close this issue for now. Please don't hesitate to still reach out, we'd love to hear your thoughts.
