### ISSUE TITLE
SDK can't be built as a framework

### ISSUE THREAD

**Issue by dimat** [Livefyre/StreamHub-iOS-SDK#76]
If this SDK is included with cocoapods to the project that has `use_frameworks!`, then it doesn't compile because of an error in AFNetworking:
`AFNetworking/AFNetworkReachabilityManager.h:29:9: Include of non-modular header inside framework module 'AFNetworking.AFNetworkReachabilityManager'`

This has been already fixed in AFNetworking: https://github.com/AFNetworking/AFNetworking/issues/2205

Could you please update this SDK to be able to include it as framework (which is needed for Swift projects)?

**Comment by gibron** [comment]
thanks @dimat we are reviewing :)

**Comment by dimat** [comment]
There are two more issues when submitting an app with StreamHub built as a framework. Apple complains that `CFBundleShortVersionString` can be only integers separated by period. Two libraries that StreamHub uses have versions `1.6a` (LFAsyncDictionary) and `0.1.0a` (LFJSONKit). Removing `a` from the version in their `Info.plist` resolves the problem.

**Comment by gibron** [comment]
@dimat  Good to know, thanks! #77 merged :)
